import { Injectable } from '@nestjs/common';
import { PrismaService } from '../../prisma/prisma.service';
import PDFDocument from 'pdfkit';

@Injectable()
export class ExportsService {
  constructor(private readonly prisma: PrismaService) {}

  /** Generate CSV of user's expenses with optional date/group/trip filters. */
  async expensesCsv(
    userId: string,
    filters: { groupId?: string; tripId?: string; from?: string; to?: string },
  ): Promise<string> {
    const expenses = await this.queryExpenses(userId, filters);

    const header = 'Date,Description,Amount,Currency,Category,Split Method,Group,Trip,Paid By';
    const rows = expenses.map((e) => {
      const amount = (e.amount / 100).toFixed(2);
      const date = e.date.toISOString().split('T')[0];
      const escapeCsv = (s: string | null | undefined) =>
        s ? `"${s.replace(/"/g, '""')}"` : '';
      return [
        date,
        escapeCsv(e.description),
        amount,
        e.currency,
        escapeCsv(e.category),
        e.splitMethod,
        escapeCsv(e.group?.name),
        escapeCsv(e.trip?.name),
        escapeCsv(e.paidBy?.firstName),
      ].join(',');
    });

    return [header, ...rows].join('\n');
  }

  /** Generate PDF report of user's expenses. */
  async expensesPdf(
    userId: string,
    filters: { groupId?: string; tripId?: string; from?: string; to?: string },
  ): Promise<Buffer> {
    const expenses = await this.queryExpenses(userId, filters);
    const user = await this.prisma.user.findUnique({ where: { id: userId } });

    return new Promise((resolve, reject) => {
      const doc = new PDFDocument({ margin: 50, size: 'A4' });
      const chunks: Buffer[] = [];
      doc.on('data', (chunk: Buffer) => chunks.push(chunk));
      doc.on('end', () => resolve(Buffer.concat(chunks)));
      doc.on('error', reject);

      // Title
      doc.fontSize(20).text('SplitEZ Expense Report', { align: 'center' });
      doc.moveDown(0.5);
      doc.fontSize(10).fillColor('#666666')
        .text(`Generated for ${user?.firstName ?? 'User'} on ${new Date().toLocaleDateString()}`, { align: 'center' });
      doc.moveDown(1);

      // Summary
      const total = expenses.reduce((sum, e) => sum + e.amount, 0);
      doc.fontSize(12).fillColor('#000000')
        .text(`Total Expenses: ${(total / 100).toFixed(2)} INR`)
        .text(`Number of Transactions: ${expenses.length}`);
      doc.moveDown(1);

      // Table header
      doc.fontSize(9).fillColor('#333333');
      const tableTop = doc.y;
      const colWidths = [70, 150, 70, 70, 80, 60];
      const headers = ['Date', 'Description', 'Amount', 'Category', 'Group/Trip', 'Paid By'];

      let x = 50;
      headers.forEach((h, i) => {
        doc.text(h, x, tableTop, { width: colWidths[i], continued: false });
        x += colWidths[i];
      });

      doc.moveTo(50, tableTop + 15).lineTo(550, tableTop + 15).stroke('#cccccc');
      doc.y = tableTop + 20;

      // Table rows
      doc.fontSize(8).fillColor('#000000');
      for (const e of expenses) {
        if (doc.y > 750) {
          doc.addPage();
          doc.y = 50;
        }
        const y = doc.y;
        x = 50;
        const row = [
          e.date.toISOString().split('T')[0],
          e.description.substring(0, 30),
          (e.amount / 100).toFixed(2),
          e.category ?? '-',
          e.group?.name ?? e.trip?.name ?? '-',
          e.paidBy?.firstName ?? '-',
        ];
        row.forEach((cell, i) => {
          doc.text(cell, x, y, { width: colWidths[i], continued: false });
          x += colWidths[i];
        });
        doc.y = y + 15;
      }

      // Footer
      doc.moveDown(2);
      doc.fontSize(8).fillColor('#999999')
        .text('Generated by SplitEZ', { align: 'center' });

      doc.end();
    });
  }

  /** Generate CSV of settlements. */
  async settlementsCsv(
    userId: string,
    filters: { groupId?: string; from?: string; to?: string },
  ): Promise<string> {
    const where: any = {
      OR: [{ fromId: userId }, { toId: userId }],
    };
    if (filters.groupId) where.groupId = filters.groupId;
    if (filters.from || filters.to) {
      where.createdAt = {};
      if (filters.from) where.createdAt.gte = new Date(filters.from);
      if (filters.to) where.createdAt.lte = new Date(filters.to);
    }

    const settlements = await this.prisma.settlement.findMany({
      where,
      include: { from: true, to: true },
      orderBy: { createdAt: 'desc' },
    });

    const header = 'Date,From,To,Amount,Currency,Status,Note';
    const rows = settlements.map((s) => {
      const amount = (s.amount / 100).toFixed(2);
      const date = s.createdAt.toISOString().split('T')[0];
      return [
        date,
        `"${s.from.firstName}"`,
        `"${s.to.firstName}"`,
        amount,
        s.currency,
        s.status,
        s.note ? `"${s.note.replace(/"/g, '""')}"` : '',
      ].join(',');
    });

    return [header, ...rows].join('\n');
  }

  private async queryExpenses(
    userId: string,
    filters: { groupId?: string; tripId?: string; from?: string; to?: string },
  ) {
    const where: any = {
      isDeleted: false,
      OR: [
        { createdById: userId },
        { paidById: userId },
        { splits: { some: { userId } } },
      ],
    };
    if (filters.groupId) where.groupId = filters.groupId;
    if (filters.tripId) where.tripId = filters.tripId;
    if (filters.from || filters.to) {
      where.date = {};
      if (filters.from) where.date.gte = new Date(filters.from);
      if (filters.to) where.date.lte = new Date(filters.to);
    }

    return this.prisma.expense.findMany({
      where,
      include: { group: true, trip: true, paidBy: true },
      orderBy: { date: 'desc' },
    });
  }
}
